{{- if and (not .Values.secret.existingSecret) .Values.secret.secretValues }}
# WARNING: This secret is rendered from Helm values.
# In production use External Secrets Operator or Sealed Secrets instead.
# Never commit real secrets to values files. See docs/secrets-management.md.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-secret
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep   # don't delete on helm uninstall
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.secretValues }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
